<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.106" timestamp="2025-08-14T17:05:17.387955+08:00" hostname="mayundebijibendiannao.local"><testcase classname="" name="testcase.test_app_01_login" time="0.000"><error message="collection failure">testcase/test_app_01_login.py:4: in &lt;module&gt;
    from page.page_app_login import APPLoginPage
page/page_app_login.py:20: in &lt;module&gt;
    from webdriver import Remote
appium_local/webdriver/__init__.py:19: in &lt;module&gt;
    from .webdriver import WebDriver as Remote
appium_local/webdriver/webdriver.py:31: in &lt;module&gt;
    from appium.webdriver.common.appiumby import AppiumBy
appium_local/appium/webdriver/__init__.py:19: in &lt;module&gt;
    from .webdriver import WebDriver as Remote
appium_local/appium/webdriver/webdriver.py:33: in &lt;module&gt;
    from .appium_connection import AppiumConnection
appium_local/appium/webdriver/appium_connection.py:38: in &lt;module&gt;
    class AppiumConnection(RemoteConnection):
appium_local/appium/webdriver/appium_connection.py:49: in AppiumConnection
    user_agent = f'{PREFIX_HEADER}{library_version()} ({RemoteConnection.user_agent})'
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: type object 'RemoteConnection' has no attribute 'user_agent'</error></testcase></testsuite></testsuites>